/*
 * Created on 3 avr. 2014 ( Time 19:39:49 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.demo.web.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import org.demo.web.common.AbstractController;
import org.demo.web.common.FormMode;
import org.demo.web.common.Message;
import org.demo.web.common.MessageType;

//--- Entities
import org.demo.bean.BookOrderItem;
import org.demo.bean.BookOrder;
import org.demo.bean.Book;

//--- Services 
import org.demo.business.service.BookOrderItemService;
import org.demo.business.service.BookOrderService;
import org.demo.business.service.BookService;

//--- List Items 
import org.demo.web.listitem.BookOrderListItem;
import org.demo.web.listitem.BookListItem;

/**
 * Spring MVC controller for 'BookOrderItem' management.
 */
@Controller
@RequestMapping("/bookOrderItem")
public class BookOrderItemController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "bookOrderItem";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "bookOrderItem/form";
	private static final String JSP_LIST   = "bookOrderItem/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/bookOrderItem/create";
	private static final String SAVE_ACTION_UPDATE   = "/bookOrderItem/update";

	//--- Main entity service
	@Resource
    private BookOrderItemService bookOrderItemService; // Injected by Spring
	//--- Other service(s)
	@Resource
    private BookOrderService bookOrderService; // Injected by Spring
	@Resource
    private BookService bookService; // Injected by Spring

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public BookOrderItemController() {
		super(BookOrderItemController.class, MAIN_ENTITY_NAME );
		log("BookOrderItemController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------
	/**
	 * Populates the combo-box "items" for the referenced entity "BookOrder"
	 * @param model
	 */
	private void populateListOfBookOrderItems(Model model) {
		List<BookOrder> list = bookOrderService.findAll();
		List<BookOrderListItem> items = new LinkedList<BookOrderListItem>();
		for ( BookOrder bookOrder : list ) {
			items.add(new BookOrderListItem( bookOrder ) );
		}
		model.addAttribute("listOfBookOrderItems", items ) ;
	}

	/**
	 * Populates the combo-box "items" for the referenced entity "Book"
	 * @param model
	 */
	private void populateListOfBookItems(Model model) {
		List<Book> list = bookService.findAll();
		List<BookListItem> items = new LinkedList<BookListItem>();
		for ( Book book : list ) {
			items.add(new BookListItem( book ) );
		}
		model.addAttribute("listOfBookItems", items ) ;
	}


	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param bookOrderItem
	 */
	private void populateModel(Model model, BookOrderItem bookOrderItem, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, bookOrderItem);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
			populateListOfBookOrderItems(model);
			populateListOfBookItems(model);
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of BookOrderItem found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<BookOrderItem> list = bookOrderItemService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new BookOrderItem
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		BookOrderItem bookOrderItem = new BookOrderItem();	
		populateModel( model, bookOrderItem, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing BookOrderItem
	 * @param model Spring MVC model
	 * @param bookOrderId  primary key element
	 * @param bookId  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{bookOrderId}/{bookId}")
	public String formForUpdate(Model model, @PathVariable("bookOrderId") Integer bookOrderId, @PathVariable("bookId") Integer bookId ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		BookOrderItem bookOrderItem = bookOrderItemService.findById(bookOrderId, bookId);
		populateModel( model, bookOrderItem, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param bookOrderItem  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid BookOrderItem bookOrderItem, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				BookOrderItem bookOrderItemCreated = bookOrderItemService.create(bookOrderItem); 
				model.addAttribute(MAIN_ENTITY_NAME, bookOrderItemCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, bookOrderItem.getBookOrderId(), bookOrderItem.getBookId() );
			} else {
				populateModel( model, bookOrderItem, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "bookOrderItem.error.create", e);
			populateModel( model, bookOrderItem, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param bookOrderItem  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid BookOrderItem bookOrderItem, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				BookOrderItem bookOrderItemSaved = bookOrderItemService.update(bookOrderItem);
				model.addAttribute(MAIN_ENTITY_NAME, bookOrderItemSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, bookOrderItem.getBookOrderId(), bookOrderItem.getBookId());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, bookOrderItem, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "bookOrderItem.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, bookOrderItem, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param bookOrderId  primary key element
	 * @param bookId  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{bookOrderId}/{bookId}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("bookOrderId") Integer bookOrderId, @PathVariable("bookId") Integer bookId) {
		log("Action 'delete'" );
		try {
			bookOrderItemService.delete( bookOrderId, bookId );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "bookOrderItem.error.delete", e);
		}
		return redirectToList();
	}

}
