/*
 * Created on 3 avr. 2014 ( Time 19:39:49 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.demo.web.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import org.demo.web.common.AbstractController;
import org.demo.web.common.FormMode;
import org.demo.web.common.Message;
import org.demo.web.common.MessageType;

//--- Entities
import org.demo.bean.BookOrder;
import org.demo.bean.Shop;
import org.demo.bean.Employee;
import org.demo.bean.Customer;

//--- Services 
import org.demo.business.service.BookOrderService;
import org.demo.business.service.ShopService;
import org.demo.business.service.EmployeeService;
import org.demo.business.service.CustomerService;

//--- List Items 
import org.demo.web.listitem.ShopListItem;
import org.demo.web.listitem.EmployeeListItem;
import org.demo.web.listitem.CustomerListItem;

/**
 * Spring MVC controller for 'BookOrder' management.
 */
@Controller
@RequestMapping("/bookOrder")
public class BookOrderController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "bookOrder";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "bookOrder/form";
	private static final String JSP_LIST   = "bookOrder/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/bookOrder/create";
	private static final String SAVE_ACTION_UPDATE   = "/bookOrder/update";

	//--- Main entity service
	@Resource
    private BookOrderService bookOrderService; // Injected by Spring
	//--- Other service(s)
	@Resource
    private ShopService shopService; // Injected by Spring
	@Resource
    private EmployeeService employeeService; // Injected by Spring
	@Resource
    private CustomerService customerService; // Injected by Spring

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public BookOrderController() {
		super(BookOrderController.class, MAIN_ENTITY_NAME );
		log("BookOrderController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------
	/**
	 * Populates the combo-box "items" for the referenced entity "Shop"
	 * @param model
	 */
	private void populateListOfShopItems(Model model) {
		List<Shop> list = shopService.findAll();
		List<ShopListItem> items = new LinkedList<ShopListItem>();
		for ( Shop shop : list ) {
			items.add(new ShopListItem( shop ) );
		}
		model.addAttribute("listOfShopItems", items ) ;
	}

	/**
	 * Populates the combo-box "items" for the referenced entity "Employee"
	 * @param model
	 */
	private void populateListOfEmployeeItems(Model model) {
		List<Employee> list = employeeService.findAll();
		List<EmployeeListItem> items = new LinkedList<EmployeeListItem>();
		for ( Employee employee : list ) {
			items.add(new EmployeeListItem( employee ) );
		}
		model.addAttribute("listOfEmployeeItems", items ) ;
	}

	/**
	 * Populates the combo-box "items" for the referenced entity "Customer"
	 * @param model
	 */
	private void populateListOfCustomerItems(Model model) {
		List<Customer> list = customerService.findAll();
		List<CustomerListItem> items = new LinkedList<CustomerListItem>();
		for ( Customer customer : list ) {
			items.add(new CustomerListItem( customer ) );
		}
		model.addAttribute("listOfCustomerItems", items ) ;
	}


	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param bookOrder
	 */
	private void populateModel(Model model, BookOrder bookOrder, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, bookOrder);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
			populateListOfShopItems(model);
			populateListOfEmployeeItems(model);
			populateListOfCustomerItems(model);
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
			populateListOfShopItems(model);
			populateListOfCustomerItems(model);
			populateListOfEmployeeItems(model);
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of BookOrder found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<BookOrder> list = bookOrderService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new BookOrder
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		BookOrder bookOrder = new BookOrder();	
		populateModel( model, bookOrder, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing BookOrder
	 * @param model Spring MVC model
	 * @param id  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{id}")
	public String formForUpdate(Model model, @PathVariable("id") Integer id ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		BookOrder bookOrder = bookOrderService.findById(id);
		populateModel( model, bookOrder, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param bookOrder  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid BookOrder bookOrder, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				BookOrder bookOrderCreated = bookOrderService.create(bookOrder); 
				model.addAttribute(MAIN_ENTITY_NAME, bookOrderCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, bookOrder.getId() );
			} else {
				populateModel( model, bookOrder, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "bookOrder.error.create", e);
			populateModel( model, bookOrder, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param bookOrder  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid BookOrder bookOrder, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				BookOrder bookOrderSaved = bookOrderService.update(bookOrder);
				model.addAttribute(MAIN_ENTITY_NAME, bookOrderSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, bookOrder.getId());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, bookOrder, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "bookOrder.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, bookOrder, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param id  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{id}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("id") Integer id) {
		log("Action 'delete'" );
		try {
			bookOrderService.delete( id );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "bookOrder.error.delete", e);
		}
		return redirectToList();
	}

}
