/*
 * Created on 3 avr. 2014 ( Time 19:39:49 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.demo.web.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import org.demo.web.common.AbstractController;
import org.demo.web.common.FormMode;
import org.demo.web.common.Message;
import org.demo.web.common.MessageType;

//--- Entities
import org.demo.bean.Employee;
import org.demo.bean.Shop;
import org.demo.bean.Workgroup;
import org.demo.bean.Badge;

//--- Services 
import org.demo.business.service.EmployeeService;
import org.demo.business.service.ShopService;
import org.demo.business.service.WorkgroupService;
import org.demo.business.service.BadgeService;

//--- List Items 
import org.demo.web.listitem.ShopListItem;
import org.demo.web.listitem.WorkgroupListItem;
import org.demo.web.listitem.BadgeListItem;

/**
 * Spring MVC controller for 'Employee' management.
 */
@Controller
@RequestMapping("/employee")
public class EmployeeController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "employee";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "employee/form";
	private static final String JSP_LIST   = "employee/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/employee/create";
	private static final String SAVE_ACTION_UPDATE   = "/employee/update";

	//--- Main entity service
	@Resource
    private EmployeeService employeeService; // Injected by Spring
	//--- Other service(s)
	@Resource
    private ShopService shopService; // Injected by Spring
	@Resource
    private WorkgroupService workgroupService; // Injected by Spring
	@Resource
    private BadgeService badgeService; // Injected by Spring

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public EmployeeController() {
		super(EmployeeController.class, MAIN_ENTITY_NAME );
		log("EmployeeController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------
	/**
	 * Populates the combo-box "items" for the referenced entity "Shop"
	 * @param model
	 */
	private void populateListOfShopItems(Model model) {
		List<Shop> list = shopService.findAll();
		List<ShopListItem> items = new LinkedList<ShopListItem>();
		for ( Shop shop : list ) {
			items.add(new ShopListItem( shop ) );
		}
		model.addAttribute("listOfShopItems", items ) ;
	}

	/**
	 * Populates the combo-box "items" for the referenced entity "Workgroup"
	 * @param model
	 */
	private void populateListOfWorkgroupItems(Model model) {
		List<Workgroup> list = workgroupService.findAll();
		List<WorkgroupListItem> items = new LinkedList<WorkgroupListItem>();
		for ( Workgroup workgroup : list ) {
			items.add(new WorkgroupListItem( workgroup ) );
		}
		model.addAttribute("listOfWorkgroupItems", items ) ;
	}

	/**
	 * Populates the combo-box "items" for the referenced entity "Badge"
	 * @param model
	 */
	private void populateListOfBadgeItems(Model model) {
		List<Badge> list = badgeService.findAll();
		List<BadgeListItem> items = new LinkedList<BadgeListItem>();
		for ( Badge badge : list ) {
			items.add(new BadgeListItem( badge ) );
		}
		model.addAttribute("listOfBadgeItems", items ) ;
	}


	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param employee
	 */
	private void populateModel(Model model, Employee employee, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, employee);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
			populateListOfShopItems(model);
			populateListOfWorkgroupItems(model);
			populateListOfBadgeItems(model);
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
			populateListOfShopItems(model);
			populateListOfBadgeItems(model);
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of Employee found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<Employee> list = employeeService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new Employee
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		Employee employee = new Employee();	
		populateModel( model, employee, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing Employee
	 * @param model Spring MVC model
	 * @param code  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{code}")
	public String formForUpdate(Model model, @PathVariable("code") String code ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		Employee employee = employeeService.findById(code);
		populateModel( model, employee, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param employee  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid Employee employee, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				Employee employeeCreated = employeeService.create(employee); 
				model.addAttribute(MAIN_ENTITY_NAME, employeeCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, employee.getCode() );
			} else {
				populateModel( model, employee, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "employee.error.create", e);
			populateModel( model, employee, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param employee  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid Employee employee, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				Employee employeeSaved = employeeService.update(employee);
				model.addAttribute(MAIN_ENTITY_NAME, employeeSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, employee.getCode());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, employee, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "employee.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, employee, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param code  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{code}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("code") String code) {
		log("Action 'delete'" );
		try {
			employeeService.delete( code );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "employee.error.delete", e);
		}
		return redirectToList();
	}

}
