/*
 * Created on 3 avr. 2014 ( Time 19:39:41 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.demo.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.demo.bean.Author;
import org.demo.bean.jpa.AuthorEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class AuthorServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public AuthorServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'AuthorEntity' to 'Author'
	 * @param authorEntity
	 */
	public Author mapAuthorEntityToAuthor(AuthorEntity authorEntity) {
		if(authorEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Author author = map(authorEntity, Author.class);

		return author;
	}
	
	/**
	 * Mapping from 'Author' to 'AuthorEntity'
	 * @param author
	 * @param authorEntity
	 */
	public void mapAuthorToAuthorEntity(Author author, AuthorEntity authorEntity) {
		if(author == null) {
			return;
		}

		//--- Generic mapping 
		map(author, authorEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}