/*
 * Created on 3 avr. 2014 ( Time 19:39:41 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.demo.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.demo.bean.Badge;
import org.demo.bean.jpa.BadgeEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class BadgeServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public BadgeServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'BadgeEntity' to 'Badge'
	 * @param badgeEntity
	 */
	public Badge mapBadgeEntityToBadge(BadgeEntity badgeEntity) {
		if(badgeEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Badge badge = map(badgeEntity, Badge.class);

		return badge;
	}
	
	/**
	 * Mapping from 'Badge' to 'BadgeEntity'
	 * @param badge
	 * @param badgeEntity
	 */
	public void mapBadgeToBadgeEntity(Badge badge, BadgeEntity badgeEntity) {
		if(badge == null) {
			return;
		}

		//--- Generic mapping 
		map(badge, badgeEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}