/*
 * Created on 3 avr. 2014 ( Time 19:39:42 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.demo.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.demo.bean.Book;
import org.demo.bean.jpa.BookEntity;
import org.demo.bean.jpa.AuthorEntity;
import org.demo.bean.jpa.PublisherEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class BookServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public BookServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'BookEntity' to 'Book'
	 * @param bookEntity
	 */
	public Book mapBookEntityToBook(BookEntity bookEntity) {
		if(bookEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Book book = map(bookEntity, Book.class);

		//--- Link mapping ( link to Author )
		if(bookEntity.getAuthor() != null) {
			book.setAuthorId(bookEntity.getAuthor().getId());
		}
		//--- Link mapping ( link to Publisher )
		if(bookEntity.getPublisher() != null) {
			book.setPublisherId(bookEntity.getPublisher().getCode());
		}
		return book;
	}
	
	/**
	 * Mapping from 'Book' to 'BookEntity'
	 * @param book
	 * @param bookEntity
	 */
	public void mapBookToBookEntity(Book book, BookEntity bookEntity) {
		if(book == null) {
			return;
		}

		//--- Generic mapping 
		map(book, bookEntity);

		//--- Link mapping ( link : book )
		if( hasLinkToAuthor(book) ) {
			AuthorEntity author1 = new AuthorEntity();
			author1.setId( book.getAuthorId() );
			bookEntity.setAuthor( author1 );
		} else {
			bookEntity.setAuthor( null );
		}

		//--- Link mapping ( link : book )
		if( hasLinkToPublisher(book) ) {
			PublisherEntity publisher2 = new PublisherEntity();
			publisher2.setCode( book.getPublisherId() );
			bookEntity.setPublisher( publisher2 );
		} else {
			bookEntity.setPublisher( null );
		}

	}
	
	/**
	 * Verify that Author id is valid.
	 * @param Author Author
	 * @return boolean
	 */
	private boolean hasLinkToAuthor(Book book) {
		if(book.getAuthorId() != null) {
			return true;
		}
		return false;
	}

	/**
	 * Verify that Publisher id is valid.
	 * @param Publisher Publisher
	 * @return boolean
	 */
	private boolean hasLinkToPublisher(Book book) {
		if(book.getPublisherId() != null) {
			return true;
		}
		return false;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}