/*
 * Created on 3 avr. 2014 ( Time 19:39:42 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.demo.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.demo.bean.EmployeeGroup;
import org.demo.bean.jpa.EmployeeGroupEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class EmployeeGroupServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public EmployeeGroupServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'EmployeeGroupEntity' to 'EmployeeGroup'
	 * @param employeeGroupEntity
	 */
	public EmployeeGroup mapEmployeeGroupEntityToEmployeeGroup(EmployeeGroupEntity employeeGroupEntity) {
		if(employeeGroupEntity == null) {
			return null;
		}

		//--- Generic mapping 
		EmployeeGroup employeeGroup = map(employeeGroupEntity, EmployeeGroup.class);

		return employeeGroup;
	}
	
	/**
	 * Mapping from 'EmployeeGroup' to 'EmployeeGroupEntity'
	 * @param employeeGroup
	 * @param employeeGroupEntity
	 */
	public void mapEmployeeGroupToEmployeeGroupEntity(EmployeeGroup employeeGroup, EmployeeGroupEntity employeeGroupEntity) {
		if(employeeGroup == null) {
			return;
		}

		//--- Generic mapping 
		map(employeeGroup, employeeGroupEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}