/*
 * Created on 3 avr. 2014 ( Time 19:39:43 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.demo.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.demo.bean.Review;
import org.demo.bean.jpa.ReviewEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class ReviewServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public ReviewServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'ReviewEntity' to 'Review'
	 * @param reviewEntity
	 */
	public Review mapReviewEntityToReview(ReviewEntity reviewEntity) {
		if(reviewEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Review review = map(reviewEntity, Review.class);

		return review;
	}
	
	/**
	 * Mapping from 'Review' to 'ReviewEntity'
	 * @param review
	 * @param reviewEntity
	 */
	public void mapReviewToReviewEntity(Review review, ReviewEntity reviewEntity) {
		if(review == null) {
			return;
		}

		//--- Generic mapping 
		map(review, reviewEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}