/*
 * Created on 3 avr. 2014 ( Time 19:39:43 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.demo.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.demo.bean.Workgroup;
import org.demo.bean.jpa.WorkgroupEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class WorkgroupServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public WorkgroupServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'WorkgroupEntity' to 'Workgroup'
	 * @param workgroupEntity
	 */
	public Workgroup mapWorkgroupEntityToWorkgroup(WorkgroupEntity workgroupEntity) {
		if(workgroupEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Workgroup workgroup = map(workgroupEntity, Workgroup.class);

		return workgroup;
	}
	
	/**
	 * Mapping from 'Workgroup' to 'WorkgroupEntity'
	 * @param workgroup
	 * @param workgroupEntity
	 */
	public void mapWorkgroupToWorkgroupEntity(Workgroup workgroup, WorkgroupEntity workgroupEntity) {
		if(workgroup == null) {
			return;
		}

		//--- Generic mapping 
		map(workgroup, workgroupEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}