/*
 * Created on 3 avr. 2014 ( Time 19:39:42 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.demo.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.demo.bean.Country;
import org.demo.bean.jpa.CountryEntity;
import org.demo.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class CountryServiceMapperTest {

	private CountryServiceMapper countryServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		countryServiceMapper = new CountryServiceMapper();
		countryServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'CountryEntity' to 'Country'
	 * @param countryEntity
	 */
	@Test
	public void testMapCountryEntityToCountry() {
		// Given
		CountryEntity countryEntity = new CountryEntity();
		countryEntity.setName(mockValues.nextString(45));
		
		// When
		Country country = countryServiceMapper.mapCountryEntityToCountry(countryEntity);
		
		// Then
		assertEquals(countryEntity.getName(), country.getName());
	}
	
	/**
	 * Test : Mapping from 'Country' to 'CountryEntity'
	 */
	@Test
	public void testMapCountryToCountryEntity() {
		// Given
		Country country = new Country();
		country.setName(mockValues.nextString(45));

		CountryEntity countryEntity = new CountryEntity();
		
		// When
		countryServiceMapper.mapCountryToCountryEntity(country, countryEntity);
		
		// Then
		assertEquals(country.getName(), countryEntity.getName());
	}

}