/*
 * Created on 3 avr. 2014 ( Time 19:39:42 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.demo.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.demo.bean.EmployeeGroup;
import org.demo.bean.jpa.EmployeeGroupEntity;
import org.demo.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class EmployeeGroupServiceMapperTest {

	private EmployeeGroupServiceMapper employeeGroupServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		employeeGroupServiceMapper = new EmployeeGroupServiceMapper();
		employeeGroupServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'EmployeeGroupEntity' to 'EmployeeGroup'
	 * @param employeeGroupEntity
	 */
	@Test
	public void testMapEmployeeGroupEntityToEmployeeGroup() {
		// Given
		EmployeeGroupEntity employeeGroupEntity = new EmployeeGroupEntity();
		
		// When
		EmployeeGroup employeeGroup = employeeGroupServiceMapper.mapEmployeeGroupEntityToEmployeeGroup(employeeGroupEntity);
		
		// Then
	}
	
	/**
	 * Test : Mapping from 'EmployeeGroup' to 'EmployeeGroupEntity'
	 */
	@Test
	public void testMapEmployeeGroupToEmployeeGroupEntity() {
		// Given
		EmployeeGroup employeeGroup = new EmployeeGroup();

		EmployeeGroupEntity employeeGroupEntity = new EmployeeGroupEntity();
		
		// When
		employeeGroupServiceMapper.mapEmployeeGroupToEmployeeGroupEntity(employeeGroup, employeeGroupEntity);
		
		// Then
	}

}