/*
 * Created on 3 avr. 2014 ( Time 19:39:43 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.demo.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.demo.bean.Synopsis;
import org.demo.bean.jpa.SynopsisEntity;
import org.demo.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class SynopsisServiceMapperTest {

	private SynopsisServiceMapper synopsisServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		synopsisServiceMapper = new SynopsisServiceMapper();
		synopsisServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'SynopsisEntity' to 'Synopsis'
	 * @param synopsisEntity
	 */
	@Test
	public void testMapSynopsisEntityToSynopsis() {
		// Given
		SynopsisEntity synopsisEntity = new SynopsisEntity();
		synopsisEntity.setSynopsis(mockValues.nextString(32700));
		
		// When
		Synopsis synopsis = synopsisServiceMapper.mapSynopsisEntityToSynopsis(synopsisEntity);
		
		// Then
		assertEquals(synopsisEntity.getSynopsis(), synopsis.getSynopsis());
	}
	
	/**
	 * Test : Mapping from 'Synopsis' to 'SynopsisEntity'
	 */
	@Test
	public void testMapSynopsisToSynopsisEntity() {
		// Given
		Synopsis synopsis = new Synopsis();
		synopsis.setSynopsis(mockValues.nextString(32700));

		SynopsisEntity synopsisEntity = new SynopsisEntity();
		
		// When
		synopsisServiceMapper.mapSynopsisToSynopsisEntity(synopsis, synopsisEntity);
		
		// Then
		assertEquals(synopsis.getSynopsis(), synopsisEntity.getSynopsis());
	}

}