/*
 * Created on 3 avr. 2014 ( Time 19:39:48 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.demo.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Badge implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer badgeNumber;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    private Short authorizationLevel;


    private Date endOfValidity;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setBadgeNumber( Integer badgeNumber ) {
        this.badgeNumber = badgeNumber ;
    }

    public Integer getBadgeNumber() {
        return this.badgeNumber;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setAuthorizationLevel( Short authorizationLevel ) {
        this.authorizationLevel = authorizationLevel;
    }
    public Short getAuthorizationLevel() {
        return this.authorizationLevel;
    }

    public void setEndOfValidity( Date endOfValidity ) {
        this.endOfValidity = endOfValidity;
    }
    public Date getEndOfValidity() {
        return this.endOfValidity;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(badgeNumber);
        sb.append("|");
        sb.append(authorizationLevel);
        sb.append("|");
        sb.append(endOfValidity);
        return sb.toString(); 
    } 


}
