/*
 * Created on 3 avr. 2014 ( Time 19:39:49 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.demo.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.math.BigDecimal;

public class Book implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    private Integer publisherId;

    @NotNull
    private Integer authorId;

    @NotNull
    @Size( min = 1, max = 13 )
    private String isbn;

    @Size( max = 160 )
    private String title;


    private BigDecimal price;


    private Integer quantity;


    private Integer discount;


    private Short availability;


    private Short bestSeller;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setPublisherId( Integer publisherId ) {
        this.publisherId = publisherId;
    }
    public Integer getPublisherId() {
        return this.publisherId;
    }

    public void setAuthorId( Integer authorId ) {
        this.authorId = authorId;
    }
    public Integer getAuthorId() {
        return this.authorId;
    }

    public void setIsbn( String isbn ) {
        this.isbn = isbn;
    }
    public String getIsbn() {
        return this.isbn;
    }

    public void setTitle( String title ) {
        this.title = title;
    }
    public String getTitle() {
        return this.title;
    }

    public void setPrice( BigDecimal price ) {
        this.price = price;
    }
    public BigDecimal getPrice() {
        return this.price;
    }

    public void setQuantity( Integer quantity ) {
        this.quantity = quantity;
    }
    public Integer getQuantity() {
        return this.quantity;
    }

    public void setDiscount( Integer discount ) {
        this.discount = discount;
    }
    public Integer getDiscount() {
        return this.discount;
    }

    public void setAvailability( Short availability ) {
        this.availability = availability;
    }
    public Short getAvailability() {
        return this.availability;
    }

    public void setBestSeller( Short bestSeller ) {
        this.bestSeller = bestSeller;
    }
    public Short getBestSeller() {
        return this.bestSeller;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(publisherId);
        sb.append("|");
        sb.append(authorId);
        sb.append("|");
        sb.append(isbn);
        sb.append("|");
        sb.append(title);
        sb.append("|");
        sb.append(price);
        sb.append("|");
        sb.append(quantity);
        sb.append("|");
        sb.append(discount);
        sb.append("|");
        sb.append(availability);
        sb.append("|");
        sb.append(bestSeller);
        return sb.toString(); 
    } 


}
