/*
 * Created on 3 avr. 2014 ( Time 19:39:49 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.demo.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.math.BigDecimal;

public class BookOrderItem implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer bookOrderId;
    @NotNull
    private Integer bookId;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    private Integer quantity;

    @NotNull
    private BigDecimal price;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setBookOrderId( Integer bookOrderId ) {
        this.bookOrderId = bookOrderId ;
    }

    public Integer getBookOrderId() {
        return this.bookOrderId;
    }

    public void setBookId( Integer bookId ) {
        this.bookId = bookId ;
    }

    public Integer getBookId() {
        return this.bookId;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setQuantity( Integer quantity ) {
        this.quantity = quantity;
    }
    public Integer getQuantity() {
        return this.quantity;
    }

    public void setPrice( BigDecimal price ) {
        this.price = price;
    }
    public BigDecimal getPrice() {
        return this.price;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(bookOrderId);
        sb.append("|");
        sb.append(bookId);
        sb.append("|");
        sb.append(quantity);
        sb.append("|");
        sb.append(price);
        return sb.toString(); 
    } 


}
