/*
 * Created on 3 avr. 2014 ( Time 19:39:49 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.demo.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class BookOrder implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    @Size( min = 1, max = 3 )
    private String shopCode;

    @NotNull
    @Size( min = 1, max = 5 )
    private String customerCode;

    @NotNull
    @Size( min = 1, max = 4 )
    private String employeeCode;


    private Date date;


    private Integer state;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setShopCode( String shopCode ) {
        this.shopCode = shopCode;
    }
    public String getShopCode() {
        return this.shopCode;
    }

    public void setCustomerCode( String customerCode ) {
        this.customerCode = customerCode;
    }
    public String getCustomerCode() {
        return this.customerCode;
    }

    public void setEmployeeCode( String employeeCode ) {
        this.employeeCode = employeeCode;
    }
    public String getEmployeeCode() {
        return this.employeeCode;
    }

    public void setDate( Date date ) {
        this.date = date;
    }
    public Date getDate() {
        return this.date;
    }

    public void setState( Integer state ) {
        this.state = state;
    }
    public Integer getState() {
        return this.state;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(shopCode);
        sb.append("|");
        sb.append(customerCode);
        sb.append("|");
        sb.append(employeeCode);
        sb.append("|");
        sb.append(date);
        sb.append("|");
        sb.append(state);
        return sb.toString(); 
    } 


}
