/*
 * Created on 3 avr. 2014 ( Time 19:39:49 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.demo.bean;

import java.io.Serializable;

import javax.validation.constraints.*;


public class Employee implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    @Size( min = 1, max = 4 )
    private String code;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    @Size( min = 1, max = 3 )
    private String shopCode;

    @Size( max = 40 )
    private String firstName;

    @NotNull
    @Size( min = 1, max = 40 )
    private String lastName;


    private Short manager;


    private Integer badgeNumber;

    @Size( max = 60 )
    private String email;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setCode( String code ) {
        this.code = code ;
    }

    public String getCode() {
        return this.code;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setShopCode( String shopCode ) {
        this.shopCode = shopCode;
    }
    public String getShopCode() {
        return this.shopCode;
    }

    public void setFirstName( String firstName ) {
        this.firstName = firstName;
    }
    public String getFirstName() {
        return this.firstName;
    }

    public void setLastName( String lastName ) {
        this.lastName = lastName;
    }
    public String getLastName() {
        return this.lastName;
    }

    public void setManager( Short manager ) {
        this.manager = manager;
    }
    public Short getManager() {
        return this.manager;
    }

    public void setBadgeNumber( Integer badgeNumber ) {
        this.badgeNumber = badgeNumber;
    }
    public Integer getBadgeNumber() {
        return this.badgeNumber;
    }

    public void setEmail( String email ) {
        this.email = email;
    }
    public String getEmail() {
        return this.email;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(code);
        sb.append("|");
        sb.append(shopCode);
        sb.append("|");
        sb.append(firstName);
        sb.append("|");
        sb.append(lastName);
        sb.append("|");
        sb.append(manager);
        sb.append("|");
        sb.append(badgeNumber);
        sb.append("|");
        sb.append(email);
        return sb.toString(); 
    } 


}
