/*
 * Created on 3 avr. 2014 ( Time 19:39:50 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.demo.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Review implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    @Size( min = 1, max = 5 )
    private String customerCode;
    @NotNull
    private Integer bookId;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 32700 )
    private String reviewText;


    private Integer reviewNote;


    private Date creation;


    private Date lastUpdate;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setCustomerCode( String customerCode ) {
        this.customerCode = customerCode ;
    }

    public String getCustomerCode() {
        return this.customerCode;
    }

    public void setBookId( Integer bookId ) {
        this.bookId = bookId ;
    }

    public Integer getBookId() {
        return this.bookId;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setReviewText( String reviewText ) {
        this.reviewText = reviewText;
    }
    public String getReviewText() {
        return this.reviewText;
    }

    public void setReviewNote( Integer reviewNote ) {
        this.reviewNote = reviewNote;
    }
    public Integer getReviewNote() {
        return this.reviewNote;
    }

    public void setCreation( Date creation ) {
        this.creation = creation;
    }
    public Date getCreation() {
        return this.creation;
    }

    public void setLastUpdate( Date lastUpdate ) {
        this.lastUpdate = lastUpdate;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(customerCode);
        sb.append("|");
        sb.append(bookId);
        // attribute 'reviewText' not usable (type = String Long Text)
        sb.append("|");
        sb.append(reviewNote);
        sb.append("|");
        sb.append(creation);
        sb.append("|");
        sb.append(lastUpdate);
        return sb.toString(); 
    } 


}
