/*
 * Created on 3 avr. 2014 ( Time 19:39:37 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a composite Primary Key  


package org.demo.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "EMPLOYEE_GROUP"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="EMPLOYEE_GROUP", schema="ROOT" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="EmployeeGroupEntity.countAll", query="SELECT COUNT(x) FROM EmployeeGroupEntity x" )
} )
public class EmployeeGroupEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )  
    //----------------------------------------------------------------------
	@EmbeddedId
    private EmployeeGroupEntityKey compositePrimaryKey ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public EmployeeGroupEntity() {
		super();
		this.compositePrimaryKey = new EmployeeGroupEntityKey();       
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE COMPOSITE KEY 
    //----------------------------------------------------------------------
    public void setEmployeeCode( String employeeCode ) {
        this.compositePrimaryKey.setEmployeeCode( employeeCode ) ;
    }
    public String getEmployeeCode() {
        return this.compositePrimaryKey.getEmployeeCode() ;
    }
    public void setGroupId( Short groupId ) {
        this.compositePrimaryKey.setGroupId( groupId ) ;
    }
    public Short getGroupId() {
        return this.compositePrimaryKey.getGroupId() ;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        if ( compositePrimaryKey != null ) {  
            sb.append(compositePrimaryKey.toString());  
        }  
        else {  
            sb.append( "(null-key)" ); 
        }  
        sb.append("]:"); 
        return sb.toString(); 
    } 

}
