/*
 * Created on 3 avr. 2014 ( Time 19:39:37 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a composite Primary Key  


package org.demo.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "REVIEW"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="REVIEW", schema="ROOT" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="ReviewEntity.countAll", query="SELECT COUNT(x) FROM ReviewEntity x" )
} )
public class ReviewEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )  
    //----------------------------------------------------------------------
	@EmbeddedId
    private ReviewEntityKey compositePrimaryKey ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="REVIEW_TEXT")
    private String     reviewText   ;

    @Column(name="REVIEW_NOTE")
    private Integer    reviewNote   ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATION")
    private Date       creation     ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATE")
    private Date       lastUpdate   ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="BOOK_ID", referencedColumnName="ID", insertable=false, updatable=false)
    private BookEntity book        ;

    @ManyToOne
    @JoinColumn(name="CUSTOMER_CODE", referencedColumnName="CODE", insertable=false, updatable=false)
    private CustomerEntity customer    ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ReviewEntity() {
		super();
		this.compositePrimaryKey = new ReviewEntityKey();       
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE COMPOSITE KEY 
    //----------------------------------------------------------------------
    public void setCustomerCode( String customerCode ) {
        this.compositePrimaryKey.setCustomerCode( customerCode ) ;
    }
    public String getCustomerCode() {
        return this.compositePrimaryKey.getCustomerCode() ;
    }
    public void setBookId( Integer bookId ) {
        this.compositePrimaryKey.setBookId( bookId ) ;
    }
    public Integer getBookId() {
        return this.compositePrimaryKey.getBookId() ;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : REVIEW_TEXT ( LONG VARCHAR ) 
    public void setReviewText( String reviewText ) {
        this.reviewText = reviewText;
    }
    public String getReviewText() {
        return this.reviewText;
    }

    //--- DATABASE MAPPING : REVIEW_NOTE ( INTEGER ) 
    public void setReviewNote( Integer reviewNote ) {
        this.reviewNote = reviewNote;
    }
    public Integer getReviewNote() {
        return this.reviewNote;
    }

    //--- DATABASE MAPPING : CREATION ( TIMESTAMP ) 
    public void setCreation( Date creation ) {
        this.creation = creation;
    }
    public Date getCreation() {
        return this.creation;
    }

    //--- DATABASE MAPPING : LAST_UPDATE ( TIMESTAMP ) 
    public void setLastUpdate( Date lastUpdate ) {
        this.lastUpdate = lastUpdate;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setBook( BookEntity book ) {
        this.book = book;
    }
    public BookEntity getBook() {
        return this.book;
    }

    public void setCustomer( CustomerEntity customer ) {
        this.customer = customer;
    }
    public CustomerEntity getCustomer() {
        return this.customer;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        if ( compositePrimaryKey != null ) {  
            sb.append(compositePrimaryKey.toString());  
        }  
        else {  
            sb.append( "(null-key)" ); 
        }  
        sb.append("]:"); 
        // attribute 'reviewText' not usable (type = String Long Text)
        sb.append(reviewNote);
        sb.append("|");
        sb.append(creation);
        sb.append("|");
        sb.append(lastUpdate);
        return sb.toString(); 
    } 

}
