/*
 * Created on 3 avr. 2014 ( Time 19:39:50 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.demo.web.common;

public interface ListItem {

	public String getValue();
	
	public String getLabel();
}
