/*
 * Created on 3 avr. 2014 ( Time 19:39:49 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.demo.business.service;

import java.util.List;

import org.demo.bean.Badge;

/**
 * Business Service Interface for entity Badge.
 */
public interface BadgeService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param badgeNumber
	 * @return entity
	 */
	Badge findById( Integer badgeNumber  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Badge> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Badge save(Badge entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Badge update(Badge entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Badge create(Badge entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param badgeNumber
	 */
	void delete( Integer badgeNumber );


}
