/*
 * Created on 3 avr. 2014 ( Time 19:39:49 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.demo.business.service;

import java.util.List;

import org.demo.bean.BookOrder;

/**
 * Business Service Interface for entity BookOrder.
 */
public interface BookOrderService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	BookOrder findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<BookOrder> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	BookOrder save(BookOrder entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	BookOrder update(BookOrder entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	BookOrder create(BookOrder entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
