/*
 * Created on 3 avr. 2014 ( Time 19:39:49 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.demo.business.service;

import java.util.List;

import org.demo.bean.BookOrderItem;

/**
 * Business Service Interface for entity BookOrderItem.
 */
public interface BookOrderItemService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param bookOrderId
	 * @param bookId
	 * @return entity
	 */
	BookOrderItem findById( Integer bookOrderId, Integer bookId  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<BookOrderItem> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	BookOrderItem save(BookOrderItem entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	BookOrderItem update(BookOrderItem entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	BookOrderItem create(BookOrderItem entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param bookOrderId
	 * @param bookId
	 */
	void delete( Integer bookOrderId, Integer bookId );


}
