/*
 * Created on 3 avr. 2014 ( Time 19:39:50 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.demo.business.service;

import java.util.List;

import org.demo.bean.Shop;

/**
 * Business Service Interface for entity Shop.
 */
public interface ShopService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param code
	 * @return entity
	 */
	Shop findById( String code  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Shop> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Shop save(Shop entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Shop update(Shop entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Shop create(Shop entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param code
	 */
	void delete( String code );


}
