/*
 * Created on 3 avr. 2014 ( Time 19:39:50 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.demo.business.service;

import java.util.List;

import org.demo.bean.Workgroup;

/**
 * Business Service Interface for entity Workgroup.
 */
public interface WorkgroupService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Workgroup findById( Short id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Workgroup> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Workgroup save(Workgroup entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Workgroup update(Workgroup entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Workgroup create(Workgroup entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Short id );


}
