/*
 * Created on 3 avr. 2014 ( Time 19:39:49 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.demo.web.listitem;

import org.demo.bean.Badge;
import org.demo.web.common.ListItem;

public class BadgeListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public BadgeListItem(Badge badge) {
		super();

		this.value = ""
			 + badge.getBadgeNumber()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = badge.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
