/*
 * Created on 3 avr. 2014 ( Time 19:39:50 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.demo.web.listitem;

import org.demo.bean.Workgroup;
import org.demo.web.common.ListItem;

public class WorkgroupListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public WorkgroupListItem(Workgroup workgroup) {
		super();

		this.value = ""
			 + workgroup.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = workgroup.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
