/*
 * Created on 3 avr. 2014 ( Time 19:39:49 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.demo.rest.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.demo.bean.Employee;
import org.demo.business.service.EmployeeService;
import org.demo.web.listitem.EmployeeListItem;

/**
 * Spring MVC controller for 'Employee' management.
 */
@Controller
public class EmployeeRestController {

	@Resource
	private EmployeeService employeeService;
	
	@RequestMapping( value="/items/employee",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<EmployeeListItem> findAllAsListItems() {
		List<Employee> list = employeeService.findAll();
		List<EmployeeListItem> items = new LinkedList<EmployeeListItem>();
		for ( Employee employee : list ) {
			items.add(new EmployeeListItem( employee ) );
		}
		return items;
	}
	
	@RequestMapping( value="/employee",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<Employee> findAll() {
		return employeeService.findAll();
	}

	@RequestMapping( value="/employee/{code}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Employee findOne(@PathVariable("code") String code) {
		return employeeService.findById(code);
	}
	
	@RequestMapping( value="/employee",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Employee create(@RequestBody Employee employee) {
		return employeeService.create(employee);
	}

	@RequestMapping( value="/employee/{code}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Employee update(@PathVariable("code") String code, @RequestBody Employee employee) {
		return employeeService.update(employee);
	}

	@RequestMapping( value="/employee/{code}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("code") String code) {
		employeeService.delete(code);
	}
	
}
